FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the application code and tests into the container
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install unittest-xml-reporting httpx bcrypt psycopg2-binary redis

# Command to run the tests
CMD ["python", "-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py"]