FROM python:3.9-slim

WORKDIR /app

COPY background-worker.py /app/
COPY requirements-bg-worker.txt /app/

RUN pip install --no-cache-dir -r requirements-bg-worker.txt

CMD ["python", "background-worker.py"]